export type QuestionDifficulty = 'easy' | 'medium' | 'hard';
export interface Question { q: string; options: string[]; answer: number; difficulty: QuestionDifficulty }

export const QUESTIONS: Record<string, Question[]> = {
  Quantitative: [
    { q: 'If a train travels 240 km in 4 hours, what is its average speed?', options: ['40 km/h', '60 km/h', '80 km/h', '90 km/h'], answer: 1, difficulty: 'easy' },
    { q: 'What is 15% of 240?', options: ['24', '30', '36', '42'], answer: 2, difficulty: 'easy' },
    { q: 'A product bought for ₹800 is sold at 25% profit. What is the selling price?', options: ['₹900', '₹950', '₹1,000', '₹1,050'], answer: 2, difficulty: 'easy' },
    { q: 'What is the next number: 3, 6, 12, 24, ?', options: ['36', '42', '48', '54'], answer: 2, difficulty: 'easy' },
    { q: 'If x + 7 = 19, what is x?', options: ['10', '11', '12', '13'], answer: 2, difficulty: 'easy' },
    { q: 'A shopkeeper gives 10% discount on an item marked ₹1,500. What is the selling price?', options: ['₹1,350', '₹1,400', '₹1,450', '₹1,490'], answer: 0, difficulty: 'easy' },
    { q: 'The ratio of two numbers is 3:5 and their sum is 64. What is the smaller number?', options: ['18', '21', '24', '27'], answer: 2, difficulty: 'medium' },
    { q: 'A car covers 60 km in 45 minutes. What is its speed in km/h?', options: ['70', '75', '80', '85'], answer: 2, difficulty: 'medium' },
    { q: 'What is 25% of 25% of 160?', options: ['8', '10', '12', '16'], answer: 1, difficulty: 'medium' },
    { q: 'If the simple interest on ₹5,000 for 2 years is ₹500, what is the rate of interest per annum?', options: ['3%', '4%', '5%', '6%'], answer: 2, difficulty: 'medium' },
    { q: 'The average of 5 consecutive even numbers is 16. What is the largest number?', options: ['18', '20', '22', '24'], answer: 1, difficulty: 'medium' },
    { q: 'A man can do a piece of work in 10 days. With his friend, he can do it in 6 days. How many days will the friend alone take?', options: ['12', '15', '18', '20'], answer: 1, difficulty: 'hard' },
    { q: 'What is the compound interest on ₹10,000 at 10% per annum for 2 years?', options: ['₹2,000', '₹2,100', '₹2,200', '₹2,500'], answer: 1, difficulty: 'hard' },
    { q: 'If 3x − 5 = 16, what is x?', options: ['6', '7', '8', '9'], answer: 1, difficulty: 'easy' },
    { q: 'The area of a rectangle is 120 sq cm and its length is 12 cm. What is its perimeter?', options: ['34 cm', '40 cm', '44 cm', '48 cm'], answer: 2, difficulty: 'medium' },
    { q: 'A sum of money doubles in 8 years at simple interest. What is the rate of interest?', options: ['10%', '12.5%', '15%', '20%'], answer: 1, difficulty: 'hard' },
    { q: 'What is the next number: 1, 4, 9, 16, 25, ?', options: ['30', '36', '42', '49'], answer: 1, difficulty: 'easy' },
    { q: 'Two pipes can fill a tank in 10 and 15 minutes respectively. How long will they take together?', options: ['4 min', '5 min', '6 min', '7.5 min'], answer: 2, difficulty: 'hard' },
    { q: 'A box contains 4 red and 6 blue balls. What is the probability of drawing a red ball?', options: ['2/5', '3/5', '1/3', '1/2'], answer: 0, difficulty: 'medium' },
    { q: 'If the cost price of 8 articles equals the selling price of 10, what is the profit/loss percentage?', options: ['20% profit', '20% loss', '25% loss', '25% profit'], answer: 1, difficulty: 'hard' },
    { q: 'What is the value of √(1296) / √(16)?', options: ['7', '8', '9', '10'], answer: 2, difficulty: 'easy' },
    { q: 'A train 150 m long crosses a pole in 15 seconds. What is its speed in km/h?', options: ['30 km/h', '33 km/h', '36 km/h', '40 km/h'], answer: 2, difficulty: 'medium' },
    { q: 'What is the LCM of 12 and 18?', options: ['24', '30', '36', '48'], answer: 2, difficulty: 'medium' },
    { q: 'If a:b = 2:3 and b:c = 4:5, what is a:b:c?', options: ['6:9:10', '8:12:15', '2:3:5', '4:6:9'], answer: 1, difficulty: 'medium' },
    { q: 'A sum becomes ₹1,200 in 2 years and ₹1,320 in 3 years at simple interest. What was the sum?', options: ['₹900', '₹930', '₹960', '₹1,000'], answer: 2, difficulty: 'medium' },
    { q: 'What is the average of the first 10 natural numbers?', options: ['5', '5.5', '6', '4.5'], answer: 1, difficulty: 'medium' },
    { q: 'Two trains 120 m and 180 m long run in opposite directions at 54 km/h and 36 km/h. How long do they take to cross each other?', options: ['10 sec', '12 sec', '14 sec', '16 sec'], answer: 1, difficulty: 'hard' },
    { q: 'A alone can finish a work in 12 days, B alone in 15 days. They work together for 4 days, then A leaves. In how many days will B finish the remaining work?', options: ['4', '5', '6', '7'], answer: 2, difficulty: 'hard' },
    { q: "If the price of an item is increased by 20% and then decreased by 20%, what is the net percentage change?", options: ['No change', '-4%', '+4%', '-2%'], answer: 1, difficulty: 'hard' },
    { q: 'A sum of money at compound interest amounts to ₹4,000 in 2 years and ₹4,800 in 3 years. What is the rate of interest?', options: ['15%', '18%', '20%', '25%'], answer: 2, difficulty: 'hard' },
    { q: "The ratio of ages of A and B is 3:4. After 6 years, the ratio becomes 4:5. What is A's current age?", options: ['15', '18', '21', '24'], answer: 1, difficulty: 'hard' },
    { q: 'A bag contains 3 red, 5 green and 2 blue balls. What is the probability of NOT drawing a blue ball?', options: ['1/5', '3/5', '4/5', '9/10'], answer: 2, difficulty: 'medium' },
    { q: 'The perimeter of a square is 64 cm. What is its area?', options: ['196 sq cm', '216 sq cm', '256 sq cm', '324 sq cm'], answer: 2, difficulty: 'medium' },
    { q: 'A boat travels 30 km downstream in 2 hours and returns upstream in 3 hours. What is the speed of the boat in still water?', options: ['10 km/h', '12.5 km/h', '15 km/h', '17.5 km/h'], answer: 1, difficulty: 'hard' },
  ],
  'Logical Reasoning': [
    { q: 'Which number completes the sequence: 2, 5, 10, 17, 26, ?', options: ['35', '36', '37', '38'], answer: 2, difficulty: 'medium' },
    { q: 'If all roses are flowers and some flowers fade, which is true?', options: ['All roses fade', 'Some roses may fade', 'No roses fade', 'Roses are not flowers'], answer: 1, difficulty: 'medium' },
    { q: 'Find the odd one out.', options: ['Triangle', 'Square', 'Circle', 'Cube'], answer: 3, difficulty: 'easy' },
    { q: 'Book is to Reading as Fork is to:', options: ['Kitchen', 'Eating', 'Cooking', 'Food'], answer: 1, difficulty: 'easy' },
    { q: 'If CAT is coded as DBU, how is DOG coded?', options: ['EPH', 'EPG', 'FPI', 'DPE'], answer: 0, difficulty: 'medium' },
    { q: 'Pointing to a man, a woman said, "His mother is the only daughter of my mother." How is the woman related to the man?', options: ['Mother', 'Sister', 'Aunt', 'Grandmother'], answer: 0, difficulty: 'hard' },
    { q: 'Which number does not belong: 4, 9, 16, 23, 25, 36?', options: ['4', '16', '23', '36'], answer: 2, difficulty: 'medium' },
    { q: 'If FRIEND is coded as GSJFOE, how is CANDLE coded?', options: ['DBOEMF', 'DBOEME', 'DBPFMG', 'DCOEMF'], answer: 0, difficulty: 'hard' },
    { q: 'A clock shows 3:15. What is the angle between the hour and minute hands?', options: ['0°', '7.5°', '15°', '22.5°'], answer: 1, difficulty: 'hard' },
    { q: 'In a row of 30 children, A is 12th from the left. What is A\'s position from the right?', options: ['18th', '19th', '20th', '21st'], answer: 1, difficulty: 'easy' },
    { q: 'Statement: All books are trees. All trees are mountains. Conclusion: All books are mountains. Is the conclusion valid?', options: ['Yes', 'No', 'Cannot be determined', 'Only if trees are tall'], answer: 0, difficulty: 'easy' },
    { q: 'Find the next term: A, C, E, G, ?', options: ['H', 'I', 'J', 'K'], answer: 1, difficulty: 'easy' },
    { q: 'If 5 + 3 = 28, 9 + 1 = 810, then 7 + 2 = ?', options: ['59', '95', '14', '27'], answer: 0, difficulty: 'hard' },
    { q: 'A man walks 3 km north, turns east and walks 4 km. How far is he from the start?', options: ['5 km', '6 km', '7 km', '8 km'], answer: 0, difficulty: 'medium' },
    { q: 'Which word does NOT belong: Apple, Mango, Banana, Carrot, Grapes?', options: ['Apple', 'Mango', 'Carrot', 'Grapes'], answer: 2, difficulty: 'easy' },
    { q: 'If today is Monday, what day will it be 61 days from now?', options: ['Monday', 'Tuesday', 'Wednesday', 'Saturday'], answer: 3, difficulty: 'medium' },
    { q: 'Complete the analogy: Doctor : Hospital :: Teacher : ?', options: ['School', 'Student', 'Class', 'Education'], answer: 0, difficulty: 'easy' },
    { q: 'In a code, if WORK is written as 23-15-18-11, what is REST?', options: ['18-5-19-20', '20-5-19-18', '18-5-20-19', '19-5-18-20'], answer: 0, difficulty: 'medium' },
    { q: 'Which figure continues the series: ○, △, □, ○, △, □, ○, ?, ?', options: ['△, □', '□, ○', '○, △', '△, ○'], answer: 0, difficulty: 'easy' },
    { q: 'A is taller than B, C is shorter than A but taller than D. Who is the shortest?', options: ['A', 'B', 'C', 'D'], answer: 3, difficulty: 'medium' },
    { q: 'If "some pens are pencils" and "all pencils are erasers", which is necessarily true?', options: ['All pens are erasers', 'Some pens are erasers', 'No pens are erasers', 'All erasers are pens'], answer: 1, difficulty: 'medium' },
    { q: 'Find the missing number: 7, 14, 28, 56, ?', options: ['98', '105', '112', '120'], answer: 2, difficulty: 'medium' },
    { q: "If in a certain code, 'PAPER' is written as 'QBQFS', how is 'PENCIL' written?", options: ['QFODJM', 'QGODJM', 'PFODJM', 'QFOEJM'], answer: 0, difficulty: 'medium' },
    { q: "Ravi is twice as old as Sam was 5 years ago. If the difference between their present ages is 5 years, what is Ravi's present age?", options: ['15', '20', '25', '30'], answer: 1, difficulty: 'medium' },
    { q: 'Which one of the following numbers is different from the others: 15, 21, 28, 39?', options: ['15', '21', '28', '39'], answer: 2, difficulty: 'medium' },
    { q: 'Pointing to a photograph, a man says, "I am the only son of this man\'s father." Whose photograph is he looking at?', options: ['His own', "His father's", "His son's", "His brother's"], answer: 1, difficulty: 'medium' },
    { q: "In a certain code language, 'TRAIN' is coded as 'UQBHO'. How is 'CHAIR' coded in the same language?", options: ['DGBHS', 'DGBHR', 'CGBHS', 'DHBHS'], answer: 0, difficulty: 'hard' },
    { q: 'Introducing a woman, a man said, "She is the daughter of my grandfather\'s only son." How is the woman related to the man?', options: ['Sister', 'Daughter', 'Niece', 'Cousin'], answer: 0, difficulty: 'hard' },
    { q: 'A is the brother of B. C is the mother of A. D is the brother of E. E is the daughter of B. How is D related to C?', options: ['Son', 'Grandson', 'Nephew', 'Brother'], answer: 1, difficulty: 'hard' },
    { q: 'Sonia walks 5 km East, turns right and walks 5 km, turns right again and walks 5 km, then turns left and walks 5 km. How far is she from her starting point, and in which direction?', options: ['5 km, South', '10 km, South', '10 km, West', '15 km, South'], answer: 1, difficulty: 'hard' },
    { q: 'Statements: All pens are pencils. No pencil is an eraser. Conclusions: I. No pen is an eraser. II. Some pencils are pens. Which conclusion(s) follow?', options: ['Only I follows', 'Only II follows', 'Both I and II follow', 'Neither follows'], answer: 2, difficulty: 'hard' },
  ],
  'Verbal Ability': [
    { q: 'Choose the word closest in meaning to "meticulous".', options: ['Careless', 'Thorough', 'Fast', 'Creative'], answer: 1, difficulty: 'easy' },
    { q: 'Choose the correctly spelled word.', options: ['Accomodate', 'Acommodate', 'Accommodate', 'Acomodate'], answer: 2, difficulty: 'easy' },
    { q: 'The manager asked the team to ___ the report.', options: ['revise', 'revise it again', 'revised', 'revising'], answer: 0, difficulty: 'medium' },
    { q: 'Opposite of "scarce" is:', options: ['Rare', 'Limited', 'Abundant', 'Small'], answer: 2, difficulty: 'easy' },
    { q: 'Which sentence is grammatically correct?', options: ['She don\'t like tea.', 'She doesn\'t likes tea.', 'She doesn\'t like tea.', 'She not like tea.'], answer: 2, difficulty: 'medium' },
    { q: 'Choose the synonym of "diligent".', options: ['Lazy', 'Hardworking', 'Careless', 'Slow'], answer: 1, difficulty: 'easy' },
    { q: 'Choose the antonym of "benevolent".', options: ['Kind', 'Generous', 'Malicious', 'Honest'], answer: 2, difficulty: 'medium' },
    { q: 'Fill in the blank: "She has been working here ___ five years."', options: ['since', 'for', 'from', 'at'], answer: 1, difficulty: 'medium' },
    { q: 'Which word means "to make easier or less difficult"?', options: ['Facilitate', 'Complicate', 'Hinder', 'Impede'], answer: 0, difficulty: 'medium' },
    { q: 'Identify the correct sentence.', options: ['He go to school daily.', 'He goes to school daily.', 'He going to school daily.', 'He gone to school daily.'], answer: 1, difficulty: 'easy' },
    { q: 'Choose the correct spelling.', options: ['Neccessary', 'Necessary', 'Neccesary', 'Necesary'], answer: 1, difficulty: 'easy' },
    { q: 'What is the meaning of the idiom "a piece of cake"?', options: ['Very difficult', 'Very easy', 'A dessert', 'A small portion'], answer: 1, difficulty: 'easy' },
    { q: 'Choose the correct article: "I saw ___ honest man."', options: ['a', 'an', 'the', 'no article'], answer: 1, difficulty: 'medium' },
    { q: 'Which is a synonym for "abundant"?', options: ['Plentiful', 'Scarce', 'Empty', 'Minimal'], answer: 0, difficulty: 'easy' },
    { q: 'Rearrange: "always / on time / she / arrives". Which is correct?', options: ['She arrives always on time.', 'Always she arrives on time.', 'She always arrives on time.', 'She on time always arrives.'], answer: 2, difficulty: 'medium' },
    { q: 'Choose the correct form: "Neither of the boys ___ present."', options: ['was', 'were', 'are', 'have'], answer: 0, difficulty: 'hard' },
    { q: 'What is the antonym of "transparent"?', options: ['Clear', 'Opaque', 'Visible', 'Bright'], answer: 1, difficulty: 'medium' },
    { q: 'Fill in the blank: "The committee ___ divided on the issue."', options: ['is', 'are', 'was being', 'be'], answer: 0, difficulty: 'hard' },
    { q: 'Choose the word closest in meaning to "ephemeral".', options: ['Eternal', 'Short-lived', 'Strong', 'Permanent'], answer: 1, difficulty: 'hard' },
    { q: 'Which sentence uses the correct preposition?', options: ['He is good at math.', 'He is good in math.', 'He is good on math.', 'He is good with math.'], answer: 0, difficulty: 'medium' },
    { q: 'Choose the correct passive voice: "She wrote a letter."', options: ['A letter was written by her.', 'A letter is written by her.', 'A letter has been written by her.', 'A letter was being written by her.'], answer: 0, difficulty: 'hard' },
    { q: 'Choose the correct synonym of "candid".', options: ['Frank', 'Secretive', 'Dishonest', 'Reserved'], answer: 0, difficulty: 'medium' },
    { q: 'Fill in the blank: "He is allergic ___ peanuts."', options: ['to', 'from', 'with', 'at'], answer: 0, difficulty: 'medium' },
    { q: 'Choose the correctly punctuated sentence.', options: ['Its a nice day.', "It's a nice day.", "Its' a nice day.", 'It is a nice, day.'], answer: 1, difficulty: 'medium' },
    { q: 'Choose the word opposite in meaning to "generous".', options: ['Kind', 'Stingy', 'Giving', 'Wealthy'], answer: 1, difficulty: 'medium' },
    { q: 'Identify the correctly formed plural: "The ___ were playing in the garden."', options: ['childs', 'childrens', 'children', 'childes'], answer: 2, difficulty: 'medium' },
    { q: 'Choose the word closest in meaning to "ubiquitous".', options: ['Rare', 'Omnipresent', 'Hidden', 'Unusual'], answer: 1, difficulty: 'hard' },
    { q: 'Choose the correct reported speech: He said, "I am going to the market."', options: ['He said that he is going to the market.', 'He said that he was going to the market.', 'He said that he go to the market.', 'He says that he was going to the market.'], answer: 1, difficulty: 'hard' },
    { q: 'Choose the correct meaning of the idiom "to bite the bullet".', options: ['To avoid a difficulty', 'To face a difficult situation bravely', 'To eat quickly', 'To break a promise'], answer: 1, difficulty: 'hard' },
    { q: 'Choose the correctly structured conditional sentence.', options: ['If it will rain, I will stay home.', 'If it rains, I will stay home.', 'If it rain, I stay home.', 'If it would rain, I will stay home.'], answer: 1, difficulty: 'hard' },
    { q: 'Choose the word that is spelled correctly.', options: ['Occassion', 'Occasion', 'Ocasion', 'Occaison'], answer: 1, difficulty: 'hard' },
  ],
  'Technical MCQs': [
    { q: 'Which HTTP method is typically used to partially update a resource?', options: ['GET', 'POST', 'PUT', 'PATCH'], answer: 3, difficulty: 'medium' },
    { q: 'What does CSS stand for?', options: ['Computer Style Sheets', 'Cascading Style Sheets', 'Creative Style Syntax', 'Colorful Style Sheets'], answer: 1, difficulty: 'easy' },
    { q: 'Which data structure follows LIFO?', options: ['Queue', 'Array', 'Stack', 'Tree'], answer: 2, difficulty: 'easy' },
    { q: 'What does SQL primarily help you do?', options: ['Style pages', 'Query databases', 'Compile code', 'Design networks'], answer: 1, difficulty: 'easy' },
    { q: 'Which is a JavaScript runtime?', options: ['Node.js', 'Django', 'Laravel', 'Rails'], answer: 0, difficulty: 'easy' },
    { q: 'What is the time complexity of binary search on a sorted array?', options: ['O(n)', 'O(log n)', 'O(n²)', 'O(1)'], answer: 1, difficulty: 'hard' },
    { q: 'Which protocol is used for secure communication on the web?', options: ['HTTP', 'FTP', 'HTTPS', 'SMTP'], answer: 2, difficulty: 'easy' },
    { q: 'What is the default port for HTTP?', options: ['21', '22', '80', '443'], answer: 2, difficulty: 'medium' },
    { q: 'In React, what hook is used for side effects?', options: ['useState', 'useEffect', 'useContext', 'useRef'], answer: 1, difficulty: 'medium' },
    { q: 'Which of these is NOT a JavaScript data type?', options: ['String', 'Boolean', 'Float', 'Number'], answer: 2, difficulty: 'hard' },
    { q: 'What does "git merge" do?', options: ['Combines two branches', 'Deletes a branch', 'Creates a new repo', 'Pushes code'], answer: 0, difficulty: 'easy' },
    { q: 'Which sorting algorithm has the best average time complexity?', options: ['Bubble Sort', 'Selection Sort', 'Quick Sort', 'Insertion Sort'], answer: 2, difficulty: 'hard' },
    { q: 'What is the purpose of Docker?', options: ['Design websites', 'Containerize applications', 'Write tests', 'Manage databases'], answer: 1, difficulty: 'easy' },
    { q: 'Which is NOT a REST API HTTP method?', options: ['GET', 'POST', 'FETCH', 'DELETE'], answer: 2, difficulty: 'medium' },
    { q: 'What does "npm" stand for in the Node ecosystem?', options: ['Node Package Manager', 'New Project Module', 'Network Protocol Module', 'Node Process Manager'], answer: 0, difficulty: 'easy' },
    { q: 'Which CSS property controls spacing inside an element?', options: ['margin', 'padding', 'border', 'spacing'], answer: 1, difficulty: 'easy' },
    { q: 'What is the output of: typeof null in JavaScript?', options: ['"null"', '"undefined"', '"object"', '"number"'], answer: 2, difficulty: 'hard' },
    { q: 'Which database is a NoSQL database?', options: ['PostgreSQL', 'MySQL', 'MongoDB', 'SQLite'], answer: 2, difficulty: 'easy' },
    { q: 'What does the "alt" attribute in an <img> tag provide?', options: ['Image size', 'Alternative text', 'Image source', 'Image title'], answer: 1, difficulty: 'easy' },
    { q: 'Which HTML element is used for the largest heading?', options: ['<h6>', '<head>', '<h1>', '<header>'], answer: 2, difficulty: 'easy' },
    { q: 'What is the Big-O time complexity of accessing an array element by index?', options: ['O(n)', 'O(1)', 'O(log n)', 'O(n²)'], answer: 1, difficulty: 'medium' },
    { q: 'Which SQL clause is used to filter groups after aggregation?', options: ['WHERE', 'HAVING', 'GROUP BY', 'ORDER BY'], answer: 1, difficulty: 'medium' },
    { q: 'What does API stand for?', options: ['Application Programming Interface', 'Advanced Program Integration', 'Automated Process Interface', 'Application Process Index'], answer: 0, difficulty: 'medium' },
    { q: 'Which of these is a NoSQL database type?', options: ['Relational', 'Document-based', 'Tabular', 'Normalized'], answer: 1, difficulty: 'medium' },
    { q: 'In Git, which command is used to interactively combine multiple commits into one?', options: ['git merge', 'git rebase -i', 'git commit --amend', 'git squash'], answer: 1, difficulty: 'medium' },
    { q: 'Which HTTP status code indicates "Not Found"?', options: ['200', '301', '404', '500'], answer: 2, difficulty: 'medium' },
    { q: 'What is the space complexity of merge sort?', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], answer: 2, difficulty: 'hard' },
    { q: 'Which design pattern ensures a class has only one instance?', options: ['Factory', 'Singleton', 'Observer', 'Builder'], answer: 1, difficulty: 'hard' },
    { q: 'In React, what is the purpose of the dependency array in useEffect?', options: ['To style components', 'To control when the effect re-runs', 'To define component props', 'To manage routing'], answer: 1, difficulty: 'hard' },
    { q: 'What does ACID stand for in database transactions?', options: ['Atomicity, Consistency, Isolation, Durability', 'Accuracy, Consistency, Integration, Design', 'Atomicity, Concurrency, Isolation, Data', 'Availability, Consistency, Integrity, Durability'], answer: 0, difficulty: 'hard' },
    { q: 'Which of these sorting algorithms is NOT comparison-based?', options: ['Merge Sort', 'Quick Sort', 'Counting Sort', 'Heap Sort'], answer: 2, difficulty: 'hard' },
    { q: 'What is the primary purpose of a load balancer in system design?', options: ['Encrypt data', 'Distribute traffic across multiple servers', 'Store data persistently', 'Compile code'], answer: 1, difficulty: 'hard' },
    { q: 'Which command shows the commit history in Git?', options: ['git log', 'git status', 'git diff', 'git show'], answer: 0, difficulty: 'medium' },
    { q: 'What is the purpose of an index in a database?', options: ['To enforce foreign keys', 'To speed up data retrieval', 'To encrypt data', 'To back up data'], answer: 1, difficulty: 'medium' },
    { q: "Which of these best describes 'idempotent' in the context of REST APIs?", options: ['An operation that can be called multiple times without changing the result beyond the first call', 'An operation that always fails on retry', 'An operation that requires authentication', 'An operation that caches responses'], answer: 0, difficulty: 'hard' },
    { q: "In the CAP theorem, an 'AP' system prioritizes which two properties, sacrificing consistency during a network partition?", options: ['Availability and Partition tolerance', 'Accuracy and Speed', 'Durability and Isolation', 'Concurrency and Atomicity'], answer: 0, difficulty: 'hard' },
    { q: 'What does the modulus operator (%) return?', options: ['The quotient of division', 'The remainder of division', 'The product', 'The square root'], answer: 1, difficulty: 'easy' },
    { q: 'Which loop structure guarantees the loop body executes at least once?', options: ['for', 'while', 'do-while', 'if'], answer: 2, difficulty: 'easy' },
    { q: 'What is the sum of the digits of 12345?', options: ['12', '14', '15', '16'], answer: 2, difficulty: 'easy' },
    { q: 'Which of these numbers is a prime number?', options: ['21', '27', '29', '33'], answer: 2, difficulty: 'easy' },
    { q: "Which condition correctly checks if a number 'n' is even?", options: ['n%2==1', 'n%2==0', 'n/2==0', 'n==2'], answer: 1, difficulty: 'easy' },
    { q: 'What is the output of 17 % 5 in most programming languages?', options: ['1', '2', '3', '5'], answer: 1, difficulty: 'easy' },
    { q: "How many vowels are in the string 'INTERVIEW'?", options: ['3', '4', '5', '6'], answer: 1, difficulty: 'medium' },
    { q: 'Which of these strings is a palindrome?', options: ['LEVEL', 'WORLD', 'STUDY', 'PLANE'], answer: 0, difficulty: 'medium' },
    { q: 'Removing all vowels from the string "HELLO" leaves which result?', options: ['HLL', 'HELL', 'HLLO', 'HL'], answer: 0, difficulty: 'medium' },
    { q: 'A 2D array is declared as int a[4][5]. How many total elements does it hold?', options: ['9', '15', '20', '25'], answer: 2, difficulty: 'medium' },
    { q: "What is the transpose of a matrix's dimensions if the original matrix is 2x3?", options: ['2x3', '3x2', '2x2', '3x3'], answer: 1, difficulty: 'medium' },
    { q: 'What is the time complexity of a nested loop that iterates over an n x n matrix once per cell?', options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(2^n)'], answer: 2, difficulty: 'medium' },
    { q: 'Checking whether parentheses in an expression are balanced is a classic use case for which data structure?', options: ['Queue', 'Stack', 'Array', 'Linked List'], answer: 1, difficulty: 'medium' },
    { q: 'Which sorting technique repeatedly swaps adjacent elements if they are in the wrong order?', options: ['Merge Sort', 'Bubble Sort', 'Quick Sort', 'Heap Sort'], answer: 1, difficulty: 'medium' },
    { q: 'Given int a[3][3] filled so that a[i][j] = i*3 + j, what is the value of a[1][2]?', options: ['3', '4', '5', '6'], answer: 2, difficulty: 'hard' },
    { q: 'A 3-digit number equal to the sum of the cubes of its own digits is called a(n)?', options: ['Perfect number', 'Armstrong number', 'Prime number', 'Palindrome number'], answer: 1, difficulty: 'hard' },
    { q: 'If matrix A has dimensions 2x3 and matrix B has dimensions 3x4, what is the dimension of A×B?', options: ['2x4', '3x3', '2x3', '4x2'], answer: 0, difficulty: 'hard' },
    { q: 'What traversal approach is needed to correctly find the largest element in a 2D array?', options: ['Only traverse the first row', 'Traverse every row and column once', 'Only check diagonal elements', 'Sort each row only'], answer: 1, difficulty: 'hard' },
    { q: 'A loop runs as: for(i=5;i>0;i--) print(i). Which value does it print last?', options: ['0', '1', '5', 'It never terminates'], answer: 1, difficulty: 'hard' },
    { q: "In the nested loop: for(i=0;i<3;i++){ for(j=0;j<i;j++){ print('*') } }, how many '*' are printed in total?", options: ['2', '3', '4', '6'], answer: 1, difficulty: 'hard' },
  ],
};

// Role-specific technical banks, grouped into domains so every target role
// (40+ of them) gets genuinely relevant questions without needing one bank
// per exact title. "Technical MCQs" above is the generic fallback used when
// no target role is set or a role can't be mapped to a domain.
export const TECHNICAL_BANKS: Record<string, Question[]> = {
  'Web & Software Development': [
    { q: 'Which of these is a client-side JavaScript UI library?', options: ['Django', 'Laravel', 'React', 'Rails'], answer: 2, difficulty: 'easy' },
    { q: 'What does API stand for?', options: ['Application Programming Interface', 'Applied Program Interface', 'Advanced Programming Interface', 'Application Process Integration'], answer: 0, difficulty: 'easy' },
    { q: 'Which CSS layout module is designed for two-dimensional layouts (rows and columns together)?', options: ['Flexbox', 'Grid', 'Float', 'Table'], answer: 1, difficulty: 'easy' },
    { q: 'Which of these is a version control system?', options: ['Git', 'Docker', 'Jenkins', 'Kubernetes'], answer: 0, difficulty: 'easy' },
    { q: 'In React, which hook lets you memoize the result of an expensive calculation?', options: ['useEffect', 'useMemo', 'useCallback', 'useRef'], answer: 1, difficulty: 'medium' },
    { q: 'What does REST stand for?', options: ['Representational State Transfer', 'Remote State Transfer', 'Representational Server Transfer', 'Relational State Transfer'], answer: 0, difficulty: 'medium' },
    { q: 'Which design pattern restricts a class to a single shared instance?', options: ['Factory', 'Observer', 'Singleton', 'Adapter'], answer: 2, difficulty: 'medium' },
    { q: 'What is the main benefit of adding an index to a database column?', options: ['Reduces storage size', 'Speeds up reads at some cost to writes', 'Removes the need for a primary key', 'Encrypts the column'], answer: 1, difficulty: 'medium' },
    { q: 'What problem does a CDN primarily solve?', options: ['Database scaling', 'Reducing latency by serving content from nearby servers', 'Encrypting passwords', 'Compiling code'], answer: 1, difficulty: 'medium' },
    { q: 'What is the average time complexity of inserting into a hash map?', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], answer: 0, difficulty: 'hard' },
    { q: 'In a microservices architecture, what does "eventual consistency" mean?', options: ['Data is always instantly consistent', 'Data converges to consistency over time across services', 'Consistency is only checked at startup', 'A single shared database guarantees it'], answer: 1, difficulty: 'hard' },
    { q: 'Which HTTP status code indicates a resource was successfully created?', options: ['200', '201', '204', '301'], answer: 1, difficulty: 'hard' },
    { q: 'Which HTTP method is idempotent and safe (does not modify server state)?', options: ['GET', 'POST', 'PUT', 'DELETE'], answer: 0, difficulty: 'easy' },
    { q: 'What does DOM stand for?', options: ['Document Object Model', 'Data Object Model', 'Document Oriented Markup', 'Dynamic Object Model'], answer: 0, difficulty: 'easy' },
    { q: 'What is the purpose of a CSS preprocessor like Sass?', options: ['Compile JavaScript', 'Add variables, nesting, and mixins to CSS before compiling to plain CSS', 'Replace HTML', 'Manage databases'], answer: 1, difficulty: 'medium' },
    { q: 'In JavaScript, what does "this" refer to inside a regular function called as an object method?', options: ['The global object always', 'The object the method was called on', 'The function itself', 'undefined always'], answer: 1, difficulty: 'medium' },
    { q: 'What is the main purpose of bundling with a tool like Webpack or Vite?', options: ['Run tests', 'Combine and optimize modules/assets for the browser', 'Manage databases', 'Style components'], answer: 1, difficulty: 'medium' },
    { q: 'What problem does the virtual DOM in React primarily solve?', options: ['Eliminates the need for JavaScript', 'Minimizes expensive direct DOM manipulations by diffing and batching updates', 'Replaces CSS entirely', 'Removes the need for a build step'], answer: 1, difficulty: 'hard' },
    { q: 'In a JWT-based auth system, where should the token typically NOT be stored, to reduce XSS risk?', options: ['An httpOnly cookie', 'localStorage', 'A secure cookie with SameSite set', 'In-memory app state'], answer: 1, difficulty: 'hard' },
    { q: 'What does server-side rendering (SSR) primarily improve compared to a pure client-rendered SPA?', options: ['Database performance', 'Initial page load and SEO, since HTML arrives pre-rendered', 'CSS specificity', 'Browser compatibility only'], answer: 1, difficulty: 'hard' },
  ],
  'Mobile Development': [
    { q: 'Which language is primarily used for native iOS development?', options: ['Kotlin', 'Swift', 'Dart', 'Java'], answer: 1, difficulty: 'easy' },
    { q: 'Which language is primarily used for modern native Android development?', options: ['Kotlin', 'Swift', 'Objective-C', 'Dart'], answer: 0, difficulty: 'easy' },
    { q: 'What does React Native primarily let you build?', options: ['Only Android apps', 'Only iOS apps', 'Cross-platform mobile apps with JavaScript', 'Web apps only'], answer: 2, difficulty: 'easy' },
    { q: 'Which tool is commonly used for automated UI testing of mobile apps?', options: ['Appium', 'Photoshop', 'Docker', 'Figma'], answer: 0, difficulty: 'easy' },
    { q: 'In Flutter, what language is used to write app logic?', options: ['Java', 'Dart', 'Swift', 'Kotlin'], answer: 1, difficulty: 'medium' },
    { q: 'What is the purpose of a mobile app\'s splash screen?', options: ['Show ads', 'Displayed briefly while the app initializes', 'Replace the app icon', 'Handle crashes'], answer: 1, difficulty: 'medium' },
    { q: 'Which storage option best fits small key-value app preferences on mobile?', options: ['A full SQL database', 'AsyncStorage / SharedPreferences', 'An in-memory array only', 'Cloud-only storage'], answer: 1, difficulty: 'medium' },
    { q: 'What does "offline-first" mobile design mean?', options: ['The app only works with internet', 'The app works without connectivity and syncs later', 'The app has no local storage', 'The app skips authentication'], answer: 1, difficulty: 'medium' },
    { q: 'What does app store deployment typically require before release?', options: ['Code signing and store review', 'No configuration at all', 'Only a GitHub push', 'Root access to the device'], answer: 0, difficulty: 'medium' },
    { q: 'Which mobile architecture pattern separates UI, business logic, and observable state?', options: ['MVC', 'MVVM', 'Singleton', 'Monolith'], answer: 1, difficulty: 'hard' },
    { q: 'What is "jank" in mobile UI performance?', options: ['A crash', 'Visible stutter from dropped frames', 'A memory leak', 'A network timeout'], answer: 1, difficulty: 'hard' },
    { q: 'What is a common approach for syncing local mobile data with a server after being offline?', options: ['Silently ignore conflicts', 'Conflict resolution during background sync', 'Delete local data on reconnect', 'Disable the app until online'], answer: 1, difficulty: 'hard' },
    { q: 'Which company develops and maintains React Native?', options: ['Google', 'Meta (Facebook)', 'Apple', 'Microsoft'], answer: 1, difficulty: 'easy' },
    { q: 'What file format are Android apps typically packaged in for distribution?', options: ['.exe', '.apk / .aab', '.dmg', '.deb'], answer: 1, difficulty: 'easy' },
    { q: "What is the purpose of a mobile app's manifest file (e.g. AndroidManifest.xml)?", options: ['Store user data', "Declare the app's components, permissions, and configuration", 'Compile the app', 'Style the UI'], answer: 1, difficulty: 'medium' },
    { q: 'What does "responsive design" mean in the context of mobile apps?', options: ['Fast API response times', 'The UI adapts its layout to different screen sizes', 'Push notifications only', 'Offline-first only'], answer: 1, difficulty: 'medium' },
    { q: 'Which testing approach runs a mobile app on real or emulated devices to verify UI behavior?', options: ['Unit testing', 'UI / instrumentation testing', 'Static analysis', 'Linting'], answer: 1, difficulty: 'medium' },
    { q: 'What is "deep linking" in mobile apps?', options: ['Encrypting app data', 'A URL that opens the app directly to specific in-app content', 'A type of push notification', 'A database migration'], answer: 1, difficulty: 'hard' },
    { q: 'What is the main tradeoff of a cross-platform framework (React Native, Flutter) vs fully native development?', options: ['There is no tradeoff', 'Faster development with a shared codebase, vs potential performance and platform-API limitations', 'Cross-platform is always faster at runtime', 'Native apps cannot access hardware'], answer: 1, difficulty: 'hard' },
    { q: 'What does "app thinning" refer to on iOS?', options: ['Reducing the app icon size', 'Delivering only the resources a specific device needs, to reduce download size', "Compressing the app's source code comments", 'Removing unused permissions only'], answer: 1, difficulty: 'hard' },
  ],
  'Data & AI': [
    { q: 'Which Python library is most associated with dataframes?', options: ['NumPy', 'Pandas', 'Matplotlib', 'Requests'], answer: 1, difficulty: 'easy' },
    { q: 'What does SQL\'s GROUP BY clause do?', options: ['Sorts rows', 'Aggregates rows that share a value', 'Filters out duplicate columns', 'Joins two tables'], answer: 1, difficulty: 'easy' },
    { q: 'Which metric is commonly used to evaluate a classification model?', options: ['RMSE', 'Accuracy', 'R-squared', 'MAE'], answer: 1, difficulty: 'easy' },
    { q: 'Which chart type is best suited for showing a trend over time?', options: ['Pie chart', 'Line chart', 'Scatter plot', 'Heatmap'], answer: 1, difficulty: 'easy' },
    { q: 'What is "overfitting" in machine learning?', options: ['The model performs well on unseen data', 'The model learns noise in training data and performs poorly on new data', 'The model trains too fast', 'The model has too few parameters'], answer: 1, difficulty: 'medium' },
    { q: 'Which technique helps reduce overfitting?', options: ['Adding more layers with no constraints', 'Regularization', 'Removing all training data', 'Increasing the learning rate indefinitely'], answer: 1, difficulty: 'medium' },
    { q: 'In a normalized relational database, what does 3NF primarily eliminate?', options: ['Primary keys', 'Transitive dependencies', 'Indexes', 'Foreign keys'], answer: 1, difficulty: 'medium' },
    { q: 'What does an ETL pipeline stand for?', options: ['Extract, Transform, Load', 'Enter, Track, Log', 'Encode, Transfer, Link', 'Evaluate, Test, Learn'], answer: 0, difficulty: 'medium' },
    { q: 'What does "feature engineering" refer to in ML?', options: ['Writing unit tests', 'Creating or transforming input variables to improve model performance', 'Deploying models to production', 'Designing UI features'], answer: 1, difficulty: 'medium' },
    { q: 'What is the main purpose of a vector database in an ML system?', options: ['Store relational tables', 'Efficient similarity search over embeddings', 'Replace SQL entirely', 'Store raw video only'], answer: 1, difficulty: 'hard' },
    { q: 'Which of these best describes "data leakage" in ML?', options: ['Losing data during transfer', 'Information from outside the training set improperly influencing the model', 'A database backup failure', 'Slow query performance'], answer: 1, difficulty: 'hard' },
    { q: 'In distributed data processing (e.g. Spark), what is a "shuffle"?', options: ['Randomizing row order for display', 'Redistributing data across partitions/nodes for operations like groupBy', 'Encrypting data at rest', 'A UI animation'], answer: 1, difficulty: 'hard' },
    { q: 'Which Python library is most associated with numerical array computing?', options: ['NumPy', 'Flask', 'Django', 'Requests'], answer: 0, difficulty: 'easy' },
    { q: 'What does CSV stand for?', options: ['Comma-Separated Values', 'Computer System Verification', 'Central Server Variable', 'Coded Sequential Values'], answer: 0, difficulty: 'easy' },
    { q: 'What does "train-test split" refer to in machine learning?', options: ['Splitting a team into two', 'Dividing data into a set to train the model and a separate set to evaluate it', 'Splitting a database into shards', 'Dividing code into modules'], answer: 1, difficulty: 'medium' },
    { q: 'What is a confusion matrix used for?', options: ['Debugging code', "Visualizing a classification model's true/false positives and negatives", 'Storing raw data', 'Encrypting predictions'], answer: 1, difficulty: 'medium' },
    { q: 'What does "normalization" typically mean when preparing data for ML?', options: ['Deleting duplicate rows only', 'Scaling numeric features to a common range', 'Converting text to uppercase', "Compressing the dataset's file size"], answer: 1, difficulty: 'medium' },
    { q: 'What is the "bias-variance tradeoff" in machine learning?', options: ['A tradeoff between training speed and accuracy', "Balancing a model's error from oversimplification (bias) against its sensitivity to training data noise (variance)", 'A database consistency tradeoff', 'A tradeoff between CPU and GPU usage'], answer: 1, difficulty: 'hard' },
    { q: 'In NLP, what does a "tokenizer" do?', options: ['Encrypts text', 'Splits text into smaller units (words/subwords) for model processing', 'Translates text automatically', 'Compresses text files'], answer: 1, difficulty: 'hard' },
    { q: 'What is "cross-validation" used to estimate?', options: ['Server response time', 'How well a model generalizes to unseen data by testing on multiple data splits', 'Database query speed', 'Network latency'], answer: 1, difficulty: 'hard' },
  ],
  'Cloud & DevOps': [
    { q: 'What is the primary purpose of Docker?', options: ['Version control', 'Package apps with dependencies into containers', 'Write CSS', 'Manage DNS'], answer: 1, difficulty: 'easy' },
    { q: 'What does CI/CD stand for?', options: ['Continuous Integration / Continuous Delivery', 'Central Index / Central Deploy', 'Code Inspection / Code Deployment', 'Container Init / Container Deploy'], answer: 0, difficulty: 'easy' },
    { q: 'In AWS, what does S3 primarily provide?', options: ['Virtual servers', 'Object storage', 'DNS management only', 'Load balancing only'], answer: 1, difficulty: 'easy' },
    { q: 'Which command-line tool is used to interact with a Kubernetes cluster?', options: ['kubectl', 'docker-compose', 'npm', 'git'], answer: 0, difficulty: 'easy' },
    { q: 'What is the purpose of Kubernetes?', options: ['Write frontend code', 'Orchestrate and scale containerized applications', 'Compile source code', 'Design databases'], answer: 1, difficulty: 'medium' },
    { q: 'What is Infrastructure as Code (IaC)?', options: ['Manually clicking through a cloud console', 'Managing infrastructure through versioned configuration files', 'Writing infra documentation only', 'A monitoring dashboard'], answer: 1, difficulty: 'medium' },
    { q: 'What does a load balancer primarily do?', options: ['Encrypts traffic only', 'Distributes incoming traffic across multiple servers', 'Compiles code', 'Stores logs'], answer: 1, difficulty: 'medium' },
    { q: 'In a blue-green deployment, what is the main benefit?', options: ['Cheaper hosting', 'Near-zero-downtime releases with easy rollback', 'Faster code compilation', 'No need for monitoring'], answer: 1, difficulty: 'medium' },
    { q: 'What is the purpose of a readiness probe / health check in container orchestration?', options: ['Decorative UI', 'Determine if a container instance can safely receive traffic', 'Encrypt secrets', 'Compile images'], answer: 1, difficulty: 'medium' },
    { q: 'What problem does a service mesh (e.g. Istio) primarily address?', options: ['Writing business logic', 'Managing service-to-service traffic, security, and observability', 'Building UI components', 'Compiling containers'], answer: 1, difficulty: 'hard' },
    { q: 'What is the difference between horizontal and vertical scaling?', options: ['They mean the same thing', 'Horizontal adds more machines, vertical adds more resources to one machine', 'Horizontal only applies to databases', 'Vertical scaling is always cheaper'], answer: 1, difficulty: 'hard' },
    { q: 'What does "chaos engineering" aim to do?', options: ['Randomly break production for fun', 'Deliberately inject failures to test system resilience', 'Skip testing entirely', 'Increase deployment frequency without limits'], answer: 1, difficulty: 'hard' },
    { q: 'What does "the cloud" fundamentally refer to?', options: ['A specific physical server', 'On-demand computing resources delivered over the internet', 'A type of database only', 'A programming language'], answer: 1, difficulty: 'easy' },
    { q: 'Which of these is a major public cloud provider?', options: ['AWS', 'Photoshop', 'MySQL Workbench', 'Figma'], answer: 0, difficulty: 'easy' },
    { q: 'What is the purpose of a Dockerfile?', options: ['Style a webpage', 'A script of instructions to build a Docker image', 'Manage DNS records', 'Write unit tests'], answer: 1, difficulty: 'medium' },
    { q: 'What does "auto-scaling" in the cloud mean?', options: ['Automatically formatting code', 'Automatically adjusting compute resources based on demand', 'Automatically encrypting data', 'Automatically writing documentation'], answer: 1, difficulty: 'medium' },
    { q: 'What is the purpose of environment variables in a deployment pipeline?', options: ['Style the UI', "Configure an app's behavior/secrets per environment without changing code", 'Compile the app faster', 'Manage git branches'], answer: 1, difficulty: 'medium' },
    { q: 'What does "immutable infrastructure" mean?', options: ['Servers that can never be deleted', 'Infrastructure where servers are replaced rather than modified in place for updates', 'Infrastructure with no configuration', 'A backup strategy only'], answer: 1, difficulty: 'hard' },
    { q: 'What is the purpose of a canary deployment?', options: ['Deploying to all users at once', 'Releasing a change to a small subset of users first to catch issues before a full rollout', 'Deleting old deployments automatically', 'A type of database migration'], answer: 1, difficulty: 'hard' },
    { q: 'What does "observability" mean in a production system, beyond basic monitoring?', options: ['Only having a status page', "The ability to understand a system's internal state from its external outputs (logs, metrics, traces)", 'Watching a system through a security camera', 'Restarting servers automatically'], answer: 1, difficulty: 'hard' },
  ],
  'Cybersecurity': [
    { q: 'What does the OWASP Top 10 primarily list?', options: ['Top programming languages', 'The most critical web application security risks', 'Fastest web frameworks', 'Best UI libraries'], answer: 1, difficulty: 'easy' },
    { q: 'What is the purpose of Nmap?', options: ['Network/port scanning and host discovery', 'Writing exploits automatically', 'Encrypting traffic', 'Editing web pages'], answer: 0, difficulty: 'easy' },
    { q: 'What does SQL injection primarily exploit?', options: ['Weak passwords', 'Unsanitized user input used directly in SQL queries', 'Slow network speed', 'Outdated browsers'], answer: 1, difficulty: 'easy' },
    { q: 'What does the CIA triad in security stand for?', options: ['Confidentiality, Integrity, Availability', 'Central Intelligence Agency', 'Cyber Incident Analysis', 'Control, Integrity, Access'], answer: 0, difficulty: 'easy' },
    { q: 'What is the primary purpose of Burp Suite in web app testing?', options: ['Intercepting and manipulating HTTP traffic', 'Compiling source code', 'Managing DNS records', 'Designing UI mockups'], answer: 0, difficulty: 'medium' },
    { q: 'In penetration testing, what does "reconnaissance" refer to?', options: ['Writing the final report', 'Gathering information about the target before attacking', 'Patching vulnerabilities', 'Cleaning up logs after a test'], answer: 1, difficulty: 'medium' },
    { q: 'What does "privilege escalation" mean in an attack?', options: ['Gaining higher-level access than originally granted', 'Slowing down a network', 'Encrypting a victim\'s files', 'Registering a new domain'], answer: 0, difficulty: 'medium' },
    { q: 'What does CVE stand for in vulnerability management?', options: ['Common Vulnerabilities and Exposures', 'Critical Virus Elimination', 'Certified Vulnerability Engineer', 'Central Vulnerability Encyclopedia'], answer: 0, difficulty: 'medium' },
    { q: 'What does a firewall primarily do?', options: ['Encrypt disk storage', 'Filter network traffic based on rules', 'Compile application code', 'Store user passwords'], answer: 1, difficulty: 'medium' },
    { q: 'What is a key difference between a vulnerability scan and a penetration test?', options: ['They are identical', 'A scan identifies known issues automatically; a pentest actively exploits and validates them', 'A pentest never involves scanning', 'A scan requires exploiting systems'], answer: 1, difficulty: 'hard' },
    { q: 'In Active Directory attacks, what does "Kerberoasting" aim to obtain?', options: ['Encrypted service account password hashes for offline cracking', 'WiFi passwords', 'Physical access badges', 'Email addresses'], answer: 0, difficulty: 'hard' },
    { q: 'What is the purpose of a Metasploit "payload"?', options: ['A documentation template', 'Code executed on a target after successful exploitation', 'A network diagram', 'A firewall rule'], answer: 1, difficulty: 'hard' },
    { q: 'What does "phishing" typically involve?', options: ['Physically breaking into a server room', 'Tricking users into revealing sensitive information via fake communications', 'Overloading a server with traffic', 'Encrypting files for ransom'], answer: 1, difficulty: 'easy' },
    { q: 'What does VPN stand for?', options: ['Virtual Private Network', 'Verified Public Node', 'Virtual Protocol Node', 'Verified Private Node'], answer: 0, difficulty: 'easy' },
    { q: 'What does two-factor authentication (2FA) add on top of a password?', options: ['A second password only', 'An additional independent verification factor (e.g. OTP, biometric)', 'A CAPTCHA', 'A longer session timeout'], answer: 1, difficulty: 'medium' },
    { q: 'What is the purpose of hashing a password before storing it?', options: ['To compress it', 'To store a one-way, irreversible representation instead of the plaintext', 'To encrypt it reversibly', 'To make it shorter for the database'], answer: 1, difficulty: 'medium' },
    { q: 'What does "least privilege" mean as a security principle?', options: ['Giving every user admin access by default', 'Granting users/systems only the access they need to do their job', 'Using the cheapest cloud tier', 'Disabling all logging'], answer: 1, difficulty: 'medium' },
    { q: 'What is a "zero-day" vulnerability?', options: ['A vulnerability patched on the day of release', 'A previously unknown vulnerability with no patch available yet', 'A vulnerability affecting only day-old systems', 'A vulnerability specific to zero-trust networks'], answer: 1, difficulty: 'hard' },
    { q: 'What does "lateral movement" mean in the context of a network attack?', options: ['Moving a server to a different data center', 'An attacker moving from an initial compromised system to other systems on the network', 'Load balancing traffic sideways', 'Migrating a database horizontally'], answer: 1, difficulty: 'hard' },
    { q: 'What is the primary goal of a "defense in depth" security strategy?', options: ['Relying on a single strong firewall', 'Layering multiple independent security controls so no single failure compromises the system', 'Hiring more security staff', 'Using only open-source security tools'], answer: 1, difficulty: 'hard' },
  ],
  'QA & Testing': [
    { q: 'What is the main goal of unit testing?', options: ['Test the whole system end-to-end', 'Verify small, isolated pieces of code work correctly', 'Test UI visual design', 'Test server hardware'], answer: 1, difficulty: 'easy' },
    { q: 'What does "regression testing" verify?', options: ['New features work correctly for the first time', 'Existing functionality still works after changes', 'Only performance under load', 'Only security vulnerabilities'], answer: 1, difficulty: 'easy' },
    { q: 'Which of these is a browser automation testing tool?', options: ['Selenium', 'Photoshop', 'Docker', 'Excel'], answer: 0, difficulty: 'easy' },
    { q: 'What is the purpose of a bug tracking tool like Jira?', options: ['Compile code', 'Log, prioritize, and track defects through resolution', 'Design UI mockups', 'Manage payroll'], answer: 1, difficulty: 'easy' },
    { q: 'What is the difference between black-box and white-box testing?', options: ['Same thing, different names', 'Black-box tests without internal code knowledge; white-box tests with it', 'Black-box only tests UI colors', 'White-box only tests databases'], answer: 1, difficulty: 'medium' },
    { q: 'What is a "test case" primarily composed of?', options: ['Only the expected output', 'Preconditions, steps, and expected results', 'Only the bug ID', 'Server configuration'], answer: 1, difficulty: 'medium' },
    { q: 'What does API testing primarily validate?', options: ['Visual layout', 'Request/response behavior, status codes, and data of an API', 'Font rendering', 'Battery usage'], answer: 1, difficulty: 'medium' },
    { q: 'What is the purpose of a "smoke test"?', options: ['Deep, exhaustive testing of every feature', 'A quick check that critical functionality works before deeper testing', 'Testing only security', 'Load testing at scale'], answer: 1, difficulty: 'medium' },
    { q: 'What does "boundary value analysis" focus on testing?', options: ['Random inputs only', 'Values at the edges of valid input ranges', 'Only invalid inputs', 'UI colors'], answer: 1, difficulty: 'medium' },
    { q: 'What is test-driven development (TDD)?', options: ['Writing tests after all code is complete', 'Writing a failing test before writing the code to pass it', 'Skipping tests to move faster', 'Only testing in production'], answer: 1, difficulty: 'hard' },
    { q: 'What does a "flaky test" mean?', options: ['A test that always fails', 'A test that passes/fails inconsistently without code changes', 'A test with too many assertions', 'A test written in the wrong language'], answer: 1, difficulty: 'hard' },
    { q: 'In performance testing, what does "load testing" specifically measure?', options: ['Code readability', 'System behavior under expected concurrent user load', 'Only single-user response time', 'Database schema design'], answer: 1, difficulty: 'hard' },
    { q: 'What is the purpose of an assertion in a test?', options: ['To log a message', 'To verify an actual result matches an expected result', 'To skip a test', 'To format output'], answer: 1, difficulty: 'easy' },
    { q: 'What does "manual testing" mean?', options: ['Testing performed by a human without automation scripts', 'Testing only documentation', 'Testing performed only on manuals', 'Automated testing with AI'], answer: 0, difficulty: 'easy' },
    { q: 'What is "exploratory testing"?', options: ['Testing strictly from a pre-written script only', 'Simultaneously learning, designing, and executing tests without a fixed script', "Only testing a map/exploration feature", 'Testing done exclusively by developers'], answer: 1, difficulty: 'medium' },
    { q: 'What does "test coverage" measure?', options: ['How fast tests run', 'The proportion of code/functionality exercised by tests', 'The number of testers on a team', 'The number of bugs filed'], answer: 1, difficulty: 'medium' },
    { q: 'What is a "mock" used for in unit testing?', options: ['Making fun of bad code', "Simulating a dependency's behavior so a unit can be tested in isolation", 'Compiling test files', 'Formatting test reports'], answer: 1, difficulty: 'medium' },
    { q: 'What is "mutation testing" used to evaluate?', options: ['How fast a test suite runs', 'The quality of a test suite by introducing small code changes and checking if tests catch them', 'Server mutation/scaling', 'UI color contrast'], answer: 1, difficulty: 'hard' },
    { q: 'In CI/CD, what is the benefit of running tests in parallel across multiple stages?', options: ['It always finds more bugs', 'It reduces overall pipeline execution time', 'It replaces the need for code review', 'It increases test flakiness intentionally'], answer: 1, difficulty: 'hard' },
    { q: 'What does "shift-left testing" mean?', options: ['Testing only left-aligned UI elements', 'Moving testing earlier in the development lifecycle rather than only at the end', 'Testing only on left-handed devices', 'Reducing the QA team size'], answer: 1, difficulty: 'hard' },
  ],
  'Core Engineering': [
    { q: 'What is the SI unit of force?', options: ['Joule', 'Newton', 'Watt', 'Pascal'], answer: 1, difficulty: 'easy' },
    { q: 'In electrical circuits, what does Ohm\'s Law state?', options: ['P = VI', 'V = IR', 'F = ma', 'E = mc²'], answer: 1, difficulty: 'easy' },
    { q: 'In civil engineering, what does a "load-bearing wall" mean?', options: ['A decorative wall only', 'A wall that supports structural weight above it', 'A wall made only of glass', 'A temporary wall'], answer: 1, difficulty: 'easy' },
    { q: 'Which tool is essential for PCB design in embedded systems?', options: ['Photoshop', 'EDA/schematic capture software (e.g. KiCad, Eagle)', 'Excel', 'Word'], answer: 1, difficulty: 'easy' },
    { q: 'What is the primary purpose of a microcontroller in embedded systems?', options: ['Only display graphics', 'Execute control logic and interface with hardware peripherals', 'Store large databases', 'Run a full desktop OS'], answer: 1, difficulty: 'medium' },
    { q: 'In mechanical engineering, what does "fatigue failure" refer to?', options: ['Sudden failure under a single large load', 'Failure from repeated cyclic loading over time', 'Failure due to corrosion only', 'Failure only at high temperature'], answer: 1, difficulty: 'medium' },
    { q: 'What does UART stand for in embedded communication?', options: ['Universal Asynchronous Receiver/Transmitter', 'Unified Analog Radio Transmitter', 'Universal Array Register Type', 'United Access Real-Time'], answer: 0, difficulty: 'medium' },
    { q: 'In structural engineering, what is "reinforced concrete"?', options: ['Concrete mixed with sand only', 'Concrete strengthened internally with steel bars/rebar', 'Concrete without cement', 'Painted concrete'], answer: 1, difficulty: 'medium' },
    { q: 'What is the purpose of a factor of safety in structural design?', options: ['Reduce material cost', 'Account for uncertainties by designing beyond the expected maximum load', 'Speed up construction', 'Reduce weight only'], answer: 1, difficulty: 'medium' },
    { q: 'What is the purpose of a PID controller in embedded/control systems?', options: ['Store data permanently', 'Continuously adjust output to minimize error between setpoint and measured value', 'Compile firmware', 'Manage network traffic'], answer: 1, difficulty: 'hard' },
    { q: 'In electrical engineering, what does "power factor" signify?', options: ['Ratio of real power to apparent power in an AC circuit', 'Total voltage supplied', 'Resistance of a wire', 'Frequency of the signal'], answer: 0, difficulty: 'hard' },
    { q: 'What is the key difference between a real-time OS (RTOS) and a general-purpose OS?', options: ['No difference', 'An RTOS guarantees deterministic response times for critical tasks', 'RTOS always has a graphical interface', 'RTOS cannot run multiple tasks'], answer: 1, difficulty: 'hard' },
    { q: 'What is the SI unit of electrical current?', options: ['Volt', 'Ampere', 'Ohm', 'Watt'], answer: 1, difficulty: 'easy' },
    { q: 'In mechanical engineering, what does "torque" measure?', options: ['Rotational force', 'Linear speed', 'Temperature', 'Electrical resistance'], answer: 0, difficulty: 'easy' },
    { q: 'What is the purpose of a datasheet for an electronic component?', options: ['Marketing material only', "Documents the component's specifications, ratings, and pin configuration", 'A pricing catalog', 'A shipping label'], answer: 1, difficulty: 'medium' },
    { q: 'In civil engineering, what does "tensile strength" measure?', options: ["A material's resistance to being pulled apart", "A material's color", "A material's cost", "A material's weight only"], answer: 0, difficulty: 'medium' },
    { q: 'What does I2C stand for as a communication protocol in embedded systems?', options: ['Inter-Integrated Circuit', 'Internal Interface Connector', 'Independent Integrated Chip', 'Integrated Internet Circuit'], answer: 0, difficulty: 'medium' },
    { q: 'In control systems, what does "overshoot" refer to?', options: ['A system exceeding its target/setpoint before settling', 'A system that never reaches its setpoint', 'A hardware failure', 'A wiring error'], answer: 0, difficulty: 'hard' },
    { q: 'What is the purpose of a "watchdog timer" in embedded systems?', options: ["Track a user's login time", 'Automatically reset the system if the software becomes unresponsive', 'Measure ambient temperature', 'Count network packets'], answer: 1, difficulty: 'hard' },
    { q: 'In structural engineering, what does "moment of inertia" describe?', options: ["A material's resistance to bending/rotation based on its cross-sectional shape", 'The time it takes to build a structure', "A material's cost per unit", 'The weight of a structure'], answer: 0, difficulty: 'hard' },
  ],
  'Product & Business': [
    { q: 'What does a Product Requirements Document (PRD) primarily define?', options: ['Marketing budget only', 'What is being built, why, and for whom', 'Server architecture', 'Legal contracts'], answer: 1, difficulty: 'easy' },
    { q: 'What is a "sprint" in Agile/Scrum?', options: ['A one-time final release', 'A fixed, short time-boxed period for delivering a work increment', 'A type of bug', 'A yearly planning cycle'], answer: 1, difficulty: 'easy' },
    { q: 'What does MVP stand for in product development?', options: ['Most Valuable Player', 'Minimum Viable Product', 'Major Version Plan', 'Multi-Vendor Platform'], answer: 1, difficulty: 'easy' },
    { q: 'What is the purpose of a Gantt chart?', options: ['Show emotional sentiment', 'Visualize a project schedule and task dependencies over time', 'Track server errors', 'Design a logo'], answer: 1, difficulty: 'easy' },
    { q: 'What is the primary purpose of A/B testing?', options: ['Compare two versions to see which performs better on a metric', 'Test server load only', 'Debug code', 'Design logos'], answer: 0, difficulty: 'medium' },
    { q: 'In project management, what does a "critical path" represent?', options: ['The cheapest task sequence', 'The longest sequence of dependent tasks determining minimum project duration', 'A random task list', 'The last task only'], answer: 1, difficulty: 'medium' },
    { q: 'What is a "stakeholder" in a project?', options: ['Only the CEO', 'Any person or group with interest in or affected by the project\'s outcome', 'Only external customers', 'Only the development team'], answer: 1, difficulty: 'medium' },
    { q: 'What does "churn rate" measure in a business context?', options: ['New customer acquisition speed', 'The percentage of customers who stop using a product over a period', 'Revenue per employee', 'Server uptime'], answer: 1, difficulty: 'medium' },
    { q: 'What is the purpose of a SWOT analysis?', options: ['Financial forecasting only', 'Assessing Strengths, Weaknesses, Opportunities, and Threats', 'Scheduling tasks', 'Writing code specs'], answer: 1, difficulty: 'medium' },
    { q: 'In Scrum, what is the primary role of a Scrum Master?', options: ['Write all the code', 'Facilitate the process and remove impediments for the team', 'Own the product backlog priorities', 'Manage company finances'], answer: 1, difficulty: 'hard' },
    { q: 'What does "runway" mean for a startup?', options: ['Distance to the office', 'How long the company can operate before running out of cash', 'Marketing reach', 'Product release date'], answer: 1, difficulty: 'hard' },
    { q: 'In business analysis, what is the purpose of a "user story"?', options: ['Legal documentation', 'A short, plain-language description of a feature from an end-user\'s perspective', 'Server configuration', 'A financial report'], answer: 1, difficulty: 'hard' },
    { q: 'What does KPI stand for?', options: ['Key Performance Indicator', 'Known Product Issue', 'Key Process Improvement', 'Key Performance Investment'], answer: 0, difficulty: 'easy' },
    { q: 'What is a "backlog" in Agile product management?', options: ['Old, resolved tickets', 'A prioritized list of work not yet done', 'A server error log', 'A financial report'], answer: 1, difficulty: 'easy' },
    { q: 'What is the purpose of a "retrospective" in Scrum?', options: ["Plan the next sprint's tasks", 'Reflect on what went well or poorly in the past sprint to improve the process', 'Demo the product to stakeholders', 'Estimate story points'], answer: 1, difficulty: 'medium' },
    { q: 'What does "time to market" measure?', options: ['Employee working hours', 'How long it takes to bring a product from idea to availability for customers', 'Server response time', 'Marketing budget spent'], answer: 1, difficulty: 'medium' },
    { q: 'What is "customer segmentation" used for?', options: ['Splitting a database into shards', 'Grouping customers by shared characteristics to target them more effectively', "Encrypting customers' data", 'Reducing support tickets'], answer: 1, difficulty: 'medium' },
    { q: 'What does "product-market fit" mean?', options: ['A product having the highest possible price', 'A product satisfying strong market demand such that customers are pulling adoption', 'A perfectly bug-free product', 'A product with the most features'], answer: 1, difficulty: 'hard' },
    { q: 'In OKRs (Objectives and Key Results), what is a "Key Result"?', options: ['A qualitative aspiration', 'A measurable outcome that indicates progress toward an objective', 'A company value', 'A hiring metric'], answer: 1, difficulty: 'hard' },
    { q: 'What does "opportunity cost" mean in a business decision?', options: ['The direct monetary cost of a decision', 'The value of the next-best alternative given up when making a choice', 'The cost of hiring an opportunity manager', 'A one-time legal fee'], answer: 1, difficulty: 'hard' },
  ],
  'Design & Marketing': [
    { q: 'What does UX stand for?', options: ['User Experience', 'User Extension', 'Unified Xperience', 'User Exchange'], answer: 0, difficulty: 'easy' },
    { q: 'What is the primary purpose of wireframing?', options: ['Final polished visuals', 'A low-fidelity structural layout to plan content and flow', 'Writing backend code', 'SEO optimization'], answer: 1, difficulty: 'easy' },
    { q: 'What does SEO stand for?', options: ['Search Engine Optimization', 'Social Engagement Outreach', 'Site Efficiency Operations', 'Server Endpoint Optimization'], answer: 0, difficulty: 'easy' },
    { q: 'In content writing, what does "tone of voice" refer to?', options: ['Font size', 'The distinct personality and style used in written communication', 'Page load speed', 'Image resolution'], answer: 1, difficulty: 'easy' },
    { q: 'What is the purpose of a design system?', options: ['A single one-off mockup', 'A reusable set of components and guidelines for consistent design', 'A marketing calendar', 'A database schema'], answer: 1, difficulty: 'medium' },
    { q: 'What does accessibility (a11y) in design primarily address?', options: ['Making designs colorful', 'Making products usable by people with disabilities', 'Reducing file size', 'Faster page load only'], answer: 1, difficulty: 'medium' },
    { q: 'What is A/B testing commonly used for in marketing?', options: ['Comparing two ad/page versions to see which converts better', 'Fixing bugs', 'Compiling code', 'Managing servers'], answer: 0, difficulty: 'medium' },
    { q: 'What is the purpose of a call-to-action (CTA) in marketing content?', options: ['A legal disclaimer', 'Prompt the user to take a specific next action', 'Decorative text only', 'SEO keyword stuffing'], answer: 1, difficulty: 'medium' },
    { q: 'What does "usability testing" primarily evaluate?', options: ['Server response time', 'Whether real users can complete tasks effectively with a design', 'Code quality', 'Ad spend efficiency'], answer: 1, difficulty: 'medium' },
    { q: 'What is the purpose of user personas in product design?', options: ['Legal user agreements', 'Represent archetypes of real user groups to guide design decisions', 'Track server logs', 'Manage billing'], answer: 1, difficulty: 'hard' },
    { q: 'What is the primary goal of conversion rate optimization (CRO)?', options: ['Increase the percentage of visitors who complete a desired action', 'Increase server uptime', 'Reduce code complexity', 'Improve font rendering'], answer: 0, difficulty: 'hard' },
    { q: 'What does "design thinking" primarily emphasize?', options: ['Skipping user research', 'A human-centered, iterative process: empathize, define, ideate, prototype, test', 'Writing code first', 'Only visual aesthetics'], answer: 1, difficulty: 'hard' },
    { q: 'What does CTA typically stand for in marketing?', options: ['Call To Action', 'Content Tracking Analytics', 'Customer Target Audience', 'Click Through Average'], answer: 0, difficulty: 'easy' },
    { q: 'What is the purpose of a mood board in design?', options: ['Track team morale', 'Visually collect inspiration and style direction for a project', 'Manage project deadlines', 'Store code snippets'], answer: 1, difficulty: 'easy' },
    { q: 'What does "above the fold" mean on a webpage?', options: ['Content requiring a login', 'Content visible without scrolling', 'Content in the footer', 'Content hidden in a dropdown'], answer: 1, difficulty: 'medium' },
    { q: 'What is an A/B test primarily used to determine?', options: ['Server uptime', 'Which of two variants performs better against a specific goal', 'Code quality', 'Team productivity'], answer: 1, difficulty: 'medium' },
    { q: 'What does "brand voice" refer to?', options: ["A company's phone hotline", "The consistent personality and tone used across a brand's communication", "The CEO's speaking voice", 'A jingle used in ads'], answer: 1, difficulty: 'medium' },
    { q: 'What is the purpose of "information architecture" in UX design?', options: ['Choosing server infrastructure', 'Organizing and structuring content so users can find what they need', 'Writing backend code', 'Selecting brand colors only'], answer: 1, difficulty: 'hard' },
    { q: 'What does "customer lifetime value" (CLV) estimate?', options: ['How long a customer stays employed', 'The total revenue a business can expect from a single customer over the relationship', "A customer's age", 'The cost to acquire a customer'], answer: 1, difficulty: 'hard' },
    { q: 'What is the purpose of the "Jobs to Be Done" (JTBD) framework in product/marketing?', options: ['Assigning tasks to employees', "Understanding the underlying need a customer is \"hiring\" a product to fulfill", 'Scheduling job interviews', 'Tracking job application status'], answer: 1, difficulty: 'hard' },
  ],
};

const ROLE_TECHNICAL_DOMAIN: Record<string, string> = {
  'full stack developer': 'Web & Software Development',
  'frontend developer': 'Web & Software Development',
  'backend developer': 'Web & Software Development',
  'software architect': 'Web & Software Development',
  'web developer': 'Web & Software Development',
  'game developer': 'Web & Software Development',
  'blockchain developer': 'Web & Software Development',
  'mobile app developer': 'Mobile Development',
  'data analyst': 'Data & AI',
  'data scientist': 'Data & AI',
  'machine learning engineer': 'Data & AI',
  'ai engineer': 'Data & AI',
  'data engineer': 'Data & AI',
  'business intelligence analyst': 'Data & AI',
  'statistician': 'Data & AI',
  'devops engineer': 'Cloud & DevOps',
  'cloud engineer': 'Cloud & DevOps',
  'database administrator': 'Cloud & DevOps',
  'vapt analyst / penetration tester': 'Cybersecurity',
  'penetration tester': 'Cybersecurity',
  'cybersecurity analyst': 'Cybersecurity',
  'soc analyst': 'Cybersecurity',
  'web app security engineer': 'Cybersecurity',
  'qa / test engineer': 'QA & Testing',
  'civil engineer': 'Core Engineering',
  'mechanical engineer': 'Core Engineering',
  'electrical engineer': 'Core Engineering',
  'embedded systems engineer': 'Core Engineering',
  'product manager': 'Product & Business',
  'project manager': 'Product & Business',
  'scrum master': 'Product & Business',
  'business analyst': 'Product & Business',
  'financial analyst': 'Product & Business',
  'hr specialist': 'Product & Business',
  'operations analyst': 'Product & Business',
  'operations coordinator': 'Product & Business',
  'executive assistant': 'Product & Business',
  'ui/ux designer': 'Design & Marketing',
  'product designer': 'Design & Marketing',
  'graphic designer': 'Design & Marketing',
  'digital marketer': 'Design & Marketing',
  'content writer': 'Design & Marketing',
  'chartered accountant': 'Product & Business',
  'investment banker': 'Product & Business',
  'equity research analyst': 'Product & Business',
  'management consultant': 'Product & Business',
  'journalist': 'Design & Marketing',
  'social media manager': 'Design & Marketing',
};

// Keyword fallback for a target role picked via free-text "Other" that
// doesn't exactly match the lookup above — mirrors the category-inference
// approach already used for company matching on the server.
function inferTechnicalDomain(lowerRole: string): string | undefined {
  const has = (...words: string[]) => words.some((w) => lowerRole.includes(w));
  if (has('security', 'vapt', 'penetration', 'soc', 'cyber', 'threat')) return 'Cybersecurity';
  if (has('data', 'machine learning', 'ml ', 'ai ', 'analytics', 'statistic')) return 'Data & AI';
  if (has('devops', 'cloud', 'infra', 'database administrator', 'site reliability')) return 'Cloud & DevOps';
  if (has('qa', 'test engineer', 'quality')) return 'QA & Testing';
  if (has('mobile', 'android', 'ios', 'flutter')) return 'Mobile Development';
  if (has('civil', 'mechanical', 'electrical', 'embedded', 'hardware', 'vlsi')) return 'Core Engineering';
  if (has('product manager', 'project manager', 'scrum', 'business analyst', 'financial', 'hr ', 'operations', 'assistant', 'accountant', 'accounting', 'banker', 'banking', 'consultant', 'equity research', 'auditor', 'tax')) return 'Product & Business';
  if (has('design', 'ux', 'ui', 'marketing', 'content writer', 'graphic', 'journalist', 'social media', 'copywriter', 'video editor', 'photographer')) return 'Design & Marketing';
  if (has('developer', 'engineer', 'architect')) return 'Web & Software Development';
  return undefined;
}

export function getTechnicalDomain(targetRole?: string): string | undefined {
  if (!targetRole) return undefined;
  const key = targetRole.trim().toLowerCase();
  return ROLE_TECHNICAL_DOMAIN[key] || inferTechnicalDomain(key);
}

// Falls back to the generic "Technical MCQs" bank when no target role is set
// or it can't be mapped to a domain (e.g. Entry-Level / Trainee Associate).
export function getTechnicalBank(targetRole?: string): Question[] {
  const domain = getTechnicalDomain(targetRole);
  return (domain && TECHNICAL_BANKS[domain]) || QUESTIONS['Technical MCQs'];
}
