export const INDIAN_UNIVERSITIES: string[] = [
  'IIT Delhi', 'IIT Bombay', 'IIT Madras', 'IIT Kanpur', 'IIT Kharagpur',
  'IIT Roorkee', 'IIT Guwahati', 'IIT Hyderabad', 'IIT Indore', 'IIT (BHU) Varanasi',
  'IIT Bhubaneswar', 'IIT Gandhinagar', 'IIT Jodhpur', 'IIT Patna', 'IIT (ISM) Dhanbad',
  'IIT Bhilai', 'IIT Tirupati', 'IIT Jammu', 'IIT Dharwad', 'IIT Goa', 'IIT Palakkad',
  'IISc Bangalore', 'IIIT Hyderabad', 'IIIT Delhi', 'IIIT Bangalore', 'IIIT Allahabad',
  'IIITDM Jabalpur', 'NIT Trichy', 'NIT Surathkal', 'NIT Warangal', 'NIT Calicut',
  'NIT Rourkela', 'NIT Durgapur', 'NIT Jaipur', 'NIT Kurukshetra', 'NIT Nagpur',
  'NIT Bhopal', 'NIT Silchar', 'NIT Hamirpur', 'NIT Meghalaya', 'NIT Agartala',
  'NIT Srinagar', 'NIT Goa', 'NIT Manipur', 'NIT Mizoram', 'NIT Sikkim',
  'NIT Arunachal Pradesh', 'NIT Puducherry', 'NIT Andhra Pradesh', 'NIT Tadepalligudem',
  'BITS Pilani', 'BITS Goa', 'BITS Hyderabad', 'VIT Vellore', 'VIT Chennai',
  'VIT Bhopal', 'VIT AP', 'SRM Institute of Science and Technology', 'SRM Delhi-NCR',
  'Amrita Vishwa Vidyapeetham', 'Manipal Institute of Technology', 'Manipal University Jaipur',
  'Delhi University (DU)', 'Jawaharlal Nehru University (JNU)', 'Jamia Millia Islamia',
  'Anna University', 'University of Mumbai', 'Savitribai Phule Pune University',
  'Bangalore University', 'Osmania University', 'University of Hyderabad',
  'Calcutta University', 'Jadavpur University', 'BHU Varanasi',
  'Aligarh Muslim University', 'Christ University, Bangalore',
  'RV College of Engineering, Bangalore', 'BMS College of Engineering, Bangalore',
  'MS Ramaiah Institute of Technology', 'PES University, Bangalore',
  'Thapar Institute of Engineering & Technology', 'PEC Chandigarh',
  'SP Jain School of Global Management', 'NMIMS Mumbai', 'Symbiosis International University',
  'FLAME University, Pune', 'Krea University', 'Ashoka University',
  'OP Jindal Global University', 'Shiv Nadar University', 'Bennett University',
  'UPES Dehradun', 'Lovely Professional University (LPU)', 'Chandigarh University',
  'Amity University, Noida', 'Amity University, Mumbai', 'Woxsen University',
  'Mahindra University',
];
